app:
  server:
    host: "0.0.0.0"
    port: 25500
    read_timeout: "30s"
    write_timeout: "30s"
    max_connections: 1000
    api_mode: true
  log:
    level: "info"
    format: "json"
    output: "logs/subconverter.log"
    max_size: 100
    max_backups: 3
    max_age: 28
  cache:
    enable: true
    default_ttl: "10m"
    max_entries: 1000
    cleanup_time: "1m"
  security:
    enable_auth: false
    rate_limiting: true
    max_req_per_min: 60
    allowed_origins:
      - "*"
  monitor:
    enable_metrics: true
    metrics_path: "/metrics"
    enable_pprof: false
    pprof_path: "/debug/pprof"

rules:
  node_filters:
    - name: "remove_expired"
      type: "exclude"
      patterns:
        - "过期"
        - "到期"
        - "expired"
      regex: false
      enabled: true
    - name: "hk_nodes"
      type: "include"
      patterns:
        - "香港"
        - "HK"
        - "Hong Kong"
      regex: false
      enabled: true
  rename_rules:
    - name: "cleanup_names"
      pattern: "\\s*\\[.*?\\]\\s*"
      replacement: ""
      regex: true
      enabled: true
  region_rules:
    - name: "asia_regions"
      regions:
        - "香港"
        - "台湾"
        - "日本"
        - "新加坡"
      patterns:
        - "HK|Hong Kong|香港"
        - "TW|Taiwan|台湾"
        - "JP|Japan|日本"
        - "SG|Singapore|新加坡"
      regex: true
      enabled: true
  default_rules:
    enable_node_filter: true
    enable_rename: true
    enable_region: true
    sort_nodes: true
    udp_support: true

templates:
  client_templates:
    - name: "clash"
      type: "clash"
      file: "templates/clash/clash.yaml"
      description: "Clash 配置模板"
      enabled: true
      options:
        dns: "true"
        ipv6: "false"
    - name: "surge"
      type: "surge"
      file: "templates/surge/surge.conf"
      description: "Surge 配置模板"
      enabled: true
      options:
        dns: "true"
  default_template: "clash"
  template_dir: "templates"
  cache_templates: true
